GET http://localhost:5050/posts/653510fac2f825aeb6e05efa

####

POST http://localhost:5050/authors/create
Content-Type: application/json

{
    "firstName": "Mario",
    "lastName": "Doe",
    "email": "test@asd.it",
    "password": "asd"
}

####

POST http://localhost:5050/login
Content-Type: application/json

{
    "email": "test@test.it",
    "password": "asd"
}

####

POST http://localhost:5050/posts/create
Content-Type: application/json

{
    "category": "ciao",
    "title": "ciao",
    "cover": "ciao"
}

####

DELETE http://localhost:5050/posts/delete/653426aee168c54ba91ddd7f

####

POST http://localhost:5050/send-mail
Content-Type: application/json

{
    "to": "chimentimailertest@gmail.com"
}
